repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
        files: \.yaml$
      - id: trailing-whitespace
        exclude: (migrations/|tests/|docs/).*
      - id: end-of-file-fixer
        exclude: (migrations/|tests/|docs/).*
      - id: check-added-large-files
        exclude: (migrations/|tests/|docs/).*
      - id: check-case-conflict
        exclude: (migrations/|tests/|docs/).*
      - id: check-merge-conflict
        exclude: (migrations/|tests/|docs/).*
      - id: check-docstring-first
        exclude: (migrations/|tests/|docs/).*

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.5.1
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.5.0
    hooks:
      - id: tox-ini-fmt

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        exclude: (migrations/|tests/|docs/).*

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [ "--config=pyproject.toml" ]
        exclude: (migrations/|tests/|docs/).*

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.6.0
    hooks:
      - id: commitizen
        exclude: (migrations/|tests/|docs/).*

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: [ "-c", "pyproject.toml", "-r", "." ]
        additional_dependencies: [ "bandit[toml]" ]
        exclude: (migrations/|tests/|docs/).*

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [ "--in-place", "--recursive", "--blank" ]
        exclude: (migrations/|tests/|docs/).*

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==24.4.2
        files: '\.rst$'

  - repo: https://github.com/rstcheck/rstcheck
    rev: "v6.2.4"
    hooks:
      - id: rstcheck
        args: [ "--report-level=warning" ]
        files: ^(docs/(.*/)*.*\.rst)
        additional_dependencies: [ Sphinx==6.2.1 ]
